### ISSUE TITLE
Mark 1.20.1 as compatible

### ISSUE THREAD

**Issue by ghost** [Globox1997/HerdsPanic#5]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.21-1.20.1

### Mod Version

1.0.7

### Describe the Issue

I compiled the mod for 1.20.1 changing gradle.properties and it works perfectly fine. The mod should be updated to be compatible with both versions — 1.20, and 1.20.1.

### latest.log

N/A

**Comment by nco2k** [comment]
seems to be also working fine with 1.20.2.

**Comment by Globox1997** [comment]
Latest version is for 1.20.1
