### ISSUE TITLE
animals run for shelter regardless of setting

### ISSUE THREAD

**Issue by Thefatsparrow** [Globox1997/HerdsPanic#7]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.3

### Mod Version

1.0.7

### Describe the Issue

animals shelter when its raining even with the setting off its annoying when you have a dog whos always running away from you

### latest.log

[latest.log](https://github.com/Globox1997/HerdsPanic/files/14114908/latest.log)

### Do you use any other mods except the required ones?

yes

**Comment by DadoIrie** [comment]
can confirm - nice touch the mod, but the dog running away and being outside of the simulated junks is quite annoying when it rains - hope for a fix. until then mod is on hold on my instance

**Comment by Globox1997** [comment]
Thanks guys for the info, fixed with [https://github.com/Globox1997/HerdsPanic/commit/fdf13b3db508c7fa03ff9636d4583bce9f09fd8a](https://github.com/Globox1997/HerdsPanic/commit/fdf13b3db508c7fa03ff9636d4583bce9f09fd8a)
